# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strlen < Formula
  desc "An app that tells you the length of a string"
  homepage "https://github.com/marcos/strlen"
  version "0.0.1"
  license "BSD-3-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "ec5b65117d587c47ecf2adf9196e3d6746618e6f5fa5c6f0acee9f5677e7ec96"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_arm64.tar.gz"
      sha256 "a104a7213971bf4fa59175e7d7a520dcd2aea370777c8db0a5e3ae6a0e40eb90"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_x86_64.tar.gz"
      sha256 "a012b8fcdf3fa138c42906a8a963e6c8e7893b726f29891e15b60ae9173aa396"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_arm64.tar.gz"
      sha256 "bf5bee21666f516f0e7026435ebd6da53549c9d89b8b5e523df6a0fa794f0b54"
    end
  end

  def install
    bin.install "strlen"
  end
end
